modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "rumbly_wumbly"
version = "${version}"
displayName = "Rumbly Wumbly"
authors = "Will BL"
description = '''
Rumble
'''
#logoFile = ""

[[dependencies.rumbly_wumbly]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rumbly_wumbly]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rumbly_wumbly]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"